apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pg-prod

resources:
  - ../../base
  - pg-cluster.yaml

commonAnnotations:
  environment: prod
  managed-by: openshift-gitops
