apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mongo-prod

resources:
  - ../../base
  - mongo-cluster.yaml

patches:
  - path: og-patch.yaml

commonAnnotations:
  environment: prod
  managed-by: openshift-gitops
