apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-mongodb
  namespace: openshift-gitops
  labels:
    app: mongodb-clusters
    team: prod-team
    environment: prod
    managed-by: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: team-mongodb

  source:
    repoURL: https://github.com/john-johansson/postgres-operator-gitops-demo
    targetRevision: feature/dbaas-operators
    path: gitops/apps/mongodb/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: mongo-prod

  # Production: manual sync only
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m

  ignoreDifferences:
    - group: psmdb.percona.com
      kind: PerconaServerMongoDB
      jsonPointers:
        - /status
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
        - /status
    - group: operators.coreos.com
      kind: OperatorGroup
      jsonPointers:
        - /status
    - group: operators.coreos.com
      kind: Subscription
      jsonPointers:
        - /status
