apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pg-prod
  namespace: openshift-gitops
  labels:
    app: postgres-clusters
    team: prod-team
    environment: prod
    managed-by: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: team-postgres

  source:
    repoURL: https://github.com/john-johansson/postgres-operator-gitops-demo
    targetRevision: feature/dbaas-operators
    path: gitops/apps/postgres/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: pg-prod

  # Production: manual sync only
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m

  ignoreDifferences:
    - group: postgres-operator.crunchydata.com
      kind: PostgresCluster
      jsonPointers:
        - /status
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
        - /status
