apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mongo-dev

resources:
  - ../../base
  - mongo-cluster.yaml

patches:
  - path: og-patch.yaml

commonAnnotations:
  environment: dev
  managed-by: openshift-gitops
