---
# RoleBinding to grant dba-dev user access
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-user-binding
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Create RBAC after namespace
  namespace: dba-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: postgres-user-role
subjects:
  - kind: User
    name: dba-dev
    apiGroup: rbac.authorization.k8s.io
---
# View RoleBinding for project visibility
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dba-dev-view
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Create RBAC after namespace
  namespace: dba-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: User
    name: dba-dev
    apiGroup: rbac.authorization.k8s.io
