---
# Project for cluster infrastructure (operators, RBAC)
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-infrastructure
  namespace: openshift-gitops
spec:
  description: Cluster-wide infrastructure components (operators, RBAC, monitoring)
  
  # Source repositories
  sourceRepos:
    - https://github.com/rh-john/postgres-operator-gitops-demo
    - https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    - https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
  
  # Allowed destinations - cluster-wide namespaces only
  destinations:
    - namespace: postgres-operator
      server: https://kubernetes.default.svc
    - namespace: openshift-gitops
      server: https://kubernetes.default.svc
    - namespace: '*'  # Allow cluster-scoped resources (ClusterRoles, etc)
      server: https://kubernetes.default.svc
  
  # Cluster resource allow list (can create cluster-scoped resources)
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'apiextensions.k8s.io'
      kind: CustomResourceDefinition
    - group: 'admissionregistration.k8s.io'
      kind: ValidatingWebhookConfiguration
    - group: 'admissionregistration.k8s.io'
      kind: MutatingWebhookConfiguration
    - group: 'scheduling.k8s.io'
      kind: PriorityClass
    - group: 'user.openshift.io'
      kind: Group
  
  # Namespace resource allow list
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  
  # Orphaned resources - ignore warnings (infrastructure components manage many resources)
  orphanedResources:
    warn: false

---
# Project for database teams (DBA users)
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: postgres-databases
  namespace: openshift-gitops
spec:
  description: PostgreSQL database clusters for development teams
  
  # Source repositories
  sourceRepos:
    - https://github.com/rh-john/postgres-operator-gitops-demo
  
  # Allowed destinations - only dba-* namespaces
  destinations:
    - namespace: 'dba-*'
      server: https://kubernetes.default.svc
  
  # No cluster resources allowed (namespace-scoped only)
  clusterResourceBlacklist:
    - group: '*'
      kind: '*'
  
  # Namespace resource allow list
  namespaceResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: PersistentVolumeClaim
    - group: 'apps'
      kind: StatefulSet
    - group: 'rbac.authorization.k8s.io'
      kind: Role
    - group: 'rbac.authorization.k8s.io'
      kind: RoleBinding
    - group: 'acid.zalan.do'
      kind: postgresql
    - group: 'policy'
      kind: PodDisruptionBudget
    - group: 'networking.k8s.io'
      kind: NetworkPolicy
  
  # Orphaned resources - warn but keep (operator lifecycle)
  orphanedResources:
    warn: true

---
# Project for dev team (databases + frontend app)
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-dev
  namespace: openshift-gitops
spec:
  description: Dev team PostgreSQL databases and frontend application
  
  # Allow Applications from team namespace
  sourceNamespaces:
    - dba-dev
  
  sourceRepos:
    - https://github.com/rh-john/postgres-operator-gitops-demo
  
  # Dev namespace only
  destinations:
    - namespace: dba-dev
      server: https://kubernetes.default.svc
  
  clusterResourceBlacklist:
    - group: '*'
      kind: '*'
  
  namespaceResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: PersistentVolumeClaim
    - group: 'apps'
      kind: StatefulSet
    - group: 'apps'
      kind: Deployment
    - group: 'rbac.authorization.k8s.io'
      kind: Role
    - group: 'rbac.authorization.k8s.io'
      kind: RoleBinding
    - group: 'acid.zalan.do'
      kind: postgresql
    - group: 'policy'
      kind: PodDisruptionBudget
    - group: 'networking.k8s.io'
      kind: NetworkPolicy
    - group: 'route.openshift.io'
      kind: Route
    - group: 'build.openshift.io'
      kind: BuildConfig
    - group: 'image.openshift.io'
      kind: ImageStream
  
  orphanedResources:
    warn: true

---
# Project for test team (databases + frontend app)
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-test
  namespace: openshift-gitops
spec:
  description: Test team PostgreSQL databases and frontend application
  
  # Allow Applications from team namespace
  sourceNamespaces:
    - dba-test
  
  sourceRepos:
    - https://github.com/rh-john/postgres-operator-gitops-demo
  
  destinations:
    - namespace: dba-test
      server: https://kubernetes.default.svc
  
  clusterResourceBlacklist:
    - group: '*'
      kind: '*'
  
  namespaceResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: PersistentVolumeClaim
    - group: 'apps'
      kind: StatefulSet
    - group: 'apps'
      kind: Deployment
    - group: 'rbac.authorization.k8s.io'
      kind: Role
    - group: 'rbac.authorization.k8s.io'
      kind: RoleBinding
    - group: 'acid.zalan.do'
      kind: postgresql
    - group: 'policy'
      kind: PodDisruptionBudget
    - group: 'networking.k8s.io'
      kind: NetworkPolicy
    - group: 'route.openshift.io'
      kind: Route
    - group: 'build.openshift.io'
      kind: BuildConfig
    - group: 'image.openshift.io'
      kind: ImageStream
  
  orphanedResources:
    warn: true

---
# Project for prod team (databases + frontend app) - manual sync only
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-prod
  namespace: openshift-gitops
spec:
  description: Production team PostgreSQL databases and frontend application - manual sync only
  
  # Allow Applications from team namespace
  sourceNamespaces:
    - dba-prod
  
  sourceRepos:
    - https://github.com/rh-john/postgres-operator-gitops-demo
  
  destinations:
    - namespace: dba-prod
      server: https://kubernetes.default.svc
  
  clusterResourceBlacklist:
    - group: '*'
      kind: '*'
  
  namespaceResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: PersistentVolumeClaim
    - group: 'apps'
      kind: StatefulSet
    - group: 'apps'
      kind: Deployment
    - group: 'rbac.authorization.k8s.io'
      kind: Role
    - group: 'rbac.authorization.k8s.io'
      kind: RoleBinding
    - group: 'acid.zalan.do'
      kind: postgresql
    - group: 'policy'
      kind: PodDisruptionBudget
    - group: 'networking.k8s.io'
      kind: NetworkPolicy
    - group: 'route.openshift.io'
      kind: Route
    - group: 'build.openshift.io'
      kind: BuildConfig
    - group: 'image.openshift.io'
      kind: ImageStream
  
  orphanedResources:
    warn: true
