apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-postgres
  namespace: openshift-gitops
  labels:
    app: postgres-clusters
    team: dev-team
    environment: dev
    managed-by: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: team-postgres

  source:
    repoURL: https://github.com/john-johansson/postgres-operator-gitops-demo
    targetRevision: feature/dbaas-operators
    path: gitops/apps/postgres/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: pg-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: postgres-operator.crunchydata.com
      kind: PostgresCluster
      jsonPointers:
        - /status
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
        - /status
