apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pg-dev

resources:
  - ../../base
  - pg-cluster.yaml

commonAnnotations:
  environment: dev
  managed-by: openshift-gitops
