---
# Role for accessing PostgreSQL Operator UI
# Grants port-forward permission to postgres-operator namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-ui-access
  namespace: postgres-operator
  labels:
    app: postgres-operator
    managed-by: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  # Allow port-forwarding to UI pods
  - apiGroups:
      - ""
    resources:
      - pods/portforward
    verbs:
      - create
      - get
  
  # Need to list/get pods to identify the UI pod
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list

---
# RoleBinding for master DBA to access UI
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dba-postgres-ui-access
  namespace: postgres-operator
  labels:
    app: postgres-operator
    managed-by: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-ui-access
subjects:
  - kind: User
    name: dba
    apiGroup: rbac.authorization.k8s.io
