---
# Role for dba-test to manage ArgoCD Applications
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-app-manager-test
  namespace: openshift-gitops
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
    resourceNames:
      - test-postgres
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
  # Access to team-test project
  - apiGroups:
      - argoproj.io
    resources:
      - appprojects
    verbs:
      - get
    resourceNames:
      - team-test
---
# RoleBinding for dba-test
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dba-test-argocd-app-manager
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-app-manager-test
subjects:
  - kind: User
    name: dba-test
    apiGroup: rbac.authorization.k8s.io
