---
# Role for dba-prod to manage ArgoCD Applications
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-app-manager-prod
  namespace: openshift-gitops
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
    resourceNames:
      - prod-postgres
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
  # Access to team-prod project
  - apiGroups:
      - argoproj.io
    resources:
      - appprojects
    verbs:
      - get
    resourceNames:
      - team-prod
---
# RoleBinding for dba-prod
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dba-prod-argocd-app-manager
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-app-manager-prod
subjects:
  - kind: User
    name: dba-prod
    apiGroup: rbac.authorization.k8s.io
