---
# Role for dba-dev to manage ArgoCD Applications
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-app-manager-dev
  namespace: openshift-gitops
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
    resourceNames:
      - dev-postgres
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
  # Access to team-dev project
  - apiGroups:
      - argoproj.io
    resources:
      - appprojects
    verbs:
      - get
    resourceNames:
      - team-dev
---
# RoleBinding for dba-dev
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dba-dev-argocd-app-manager
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-app-manager-dev
subjects:
  - kind: User
    name: dba-dev
    apiGroup: rbac.authorization.k8s.io
