---
# Grant anyuid SCC to postgres-operator ServiceAccount
# Required for OpenShift - operator runs with UID 1000
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-operator-anyuid
  namespace: postgres-operator
  labels:
    app: postgres-operator
    managed-by: gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: postgres-operator
    namespace: postgres-operator
